### PR TITLE
Support for polygon holes

### PR DESCRIPTION
**Pull request by mistafunk**

### CODE REVIEW

**Review by chr11115 — APPROVED** [review]
Nice work! code looks good to me.

Just to double check:
We don't check the EO_TRIANGULATE_FACES_WITH_HOLES setting during "hole building"
The "mDetail->buildHoles" call is only made if holeCountsSize  is > 0. I assume if we just assume that if triangulateHoles is enabled then holeCountSize will be 0, correct?

**Review by chr11115 — CHANGES_REQUESTED** [review]
please resolve the issue on the CI before merging.

**Comment by mistafunk** [comment]
> Nice work! code looks good to me.
> 
> Just to double check: We don't check the EO_TRIANGULATE_FACES_WITH_HOLES setting during "hole building" The "mDetail->buildHoles" call is only made if holeCountsSize is > 0. I assume if we just assume that if triangulateHoles is enabled then holeCountSize will be 0, correct?

yes, we rely on our encoder to not produce any holes if triangulation is active.

**Review by chr11115 — APPROVED** [review]
lgtm

**Pull request merged**
